# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\learn\2021-2022-2\software industy\KWIC_BIT\GUI\kwic_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.file_Button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.file_Button.setFont(font)
        self.file_Button.setObjectName("file_Button")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.file_Button)
        self.file_broswer = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.file_broswer.setFont(font)
        self.file_broswer.setObjectName("file_broswer")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.file_broswer)
        self.gridLayout.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.origin_Button = QtWidgets.QPushButton(self.centralwidget)
        self.origin_Button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.origin_Button.setFont(font)
        self.origin_Button.setObjectName("origin_Button")
        self.gridLayout.addWidget(self.origin_Button, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sortRow_Button2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.sortRow_Button2.setFont(font)
        self.sortRow_Button2.setObjectName("sortRow_Button2")
        self.horizontalLayout.addWidget(self.sortRow_Button2)
        self.sortRow_Button = QtWidgets.QPushButton(self.centralwidget)
        self.sortRow_Button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.sortRow_Button.setFont(font)
        self.sortRow_Button.setObjectName("sortRow_Button")
        self.horizontalLayout.addWidget(self.sortRow_Button)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.shift_Button = QtWidgets.QPushButton(self.centralwidget)
        self.shift_Button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.shift_Button.setFont(font)
        self.shift_Button.setObjectName("shift_Button")
        self.gridLayout.addWidget(self.shift_Button, 4, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.find_Button = QtWidgets.QPushButton(self.centralwidget)
        self.find_Button.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.find_Button.setFont(font)
        self.find_Button.setObjectName("find_Button")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.find_Button)
        self.word_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.word_LineEdit.setFont(font)
        self.word_LineEdit.setObjectName("word_LineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.word_LineEdit)
        self.gridLayout.addLayout(self.formLayout_3, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:72pt; font-weight:600; font-style:italic;\">K W I C</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600; font-style:italic;\">by Au Yang,He LanDou,Zheng Huang,Hui LinDun</span></p></body></html>"))
        self.file_Button.setText(_translate("MainWindow", "选择文件"))
        self.file_broswer.setText(_translate("MainWindow", "D:\\learn\\\\2021-2022-2\\software industy\\KWIC_BIT\\LICENSE"))
        self.origin_Button.setText(_translate("MainWindow", "输出原文本"))
        self.sortRow_Button2.setText(_translate("MainWindow", "堆排序产生结果"))
        self.sortRow_Button.setText(_translate("MainWindow", "STL排序产生结果"))
        self.shift_Button.setText(_translate("MainWindow", "输出循环移位结果"))
        self.find_Button.setText(_translate("MainWindow", "输出查找结果"))
